app = "firefly"
primary_region = "lhr"

[build]
# image = "fireflyiii/core:version-6.1.25"
dockerfile = "Dockerfile"

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"

[[restart]]
policy = "never"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
[http_service.concurrency]
type = "requests"
soft_limit = 10000
