app = "whe"
primary_region = "lhr"

swap_size_mb = 128

[build]
# image = "fireflyiii/core:version-6.1.25"
dockerfile = "Dockerfile"

[[vm]]
size = "shared-cpu-1x"
memory = "256MB"

[[restart]]
policy = "never"

[deploy]
strategy = "immediate"

[mounts]
source = "whe_storage"
destination = "/var/www/html/storage"
initial_size = "1GB"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
[http_service.concurrency]
type = "requests"
soft_limit = 10000
[[http_service.checks]]
grace_period = "2s"
interval = "2s"
timeout = "2s"
path = "/health"
headers = { "X-Forwarded-Proto" = "HTTPS" }

[[statics]]
guest_path = "/var/www/html/public/v1"
url_prefix = "/v1"
[[statics]]
guest_path = "/var/www/html/public/v2"
url_prefix = "/v2"
[[statics]]
guest_path = "/var/www/html/public/build"
url_prefix = "/build"
[[statics]]
guest_path = "/var/www/html/public/images"
url_prefix = "/images"

[env]
APP_ENV = "local"
APP_DEBUG = "true"
DEFAULT_LANGUAGE = "en_GB"
DEFAULT_LOCALE = "equal"
TZ = "Europe/London"
LOG_CHANNEL = "stack"
APP_LOG_LEVEL = "notice"
AUDIT_LOG_LEVEL = "emergency"
DB_CONNECTION = "sqlite"
CACHE_DRIVE = "file"
SESSION_DRIVER = "file"
COOKIE_PATH = "/"
COOKIE_SECURE = "false"
COOKIE_SAMESITE = "lax"
APP_NAME = "FireflyIII"
BROADCAST_DRIVER = "log"
QUEUE_DRIVER = "sync"
CACHE_PREFIX = "firefly"
TRUSTED_PROXIES = "**"
ENABLE_EXTERNAL_MAP = "true"
ALLOW_WEBHOOKS = "true"
QUERY_PARSER_IMPLEMENTATION = "new"
