app = "firefly"
primary_region = "lhr"

[build]
# image = "fireflyiii/core:version-6.1.25"
dockerfile = "Dockerfile"

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"

[[restart]]
policy = "never"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
[http_service.concurrency]
type = "requests"
soft_limit = 10000

[env]
APP_ENV = "production"
APP_DEBUG = "true"
DEFAULT_LANGUAGE = "en_GB"
DEFAULT_LOCALE = "equal"
TZ = "Europe/London"
LOG_CHANNEL = "stack"
APP_LOG_LEVEL = "notice"
AUDIT_LOG_LEVEL = "emergency"
DB_CONNECTION = "mysql"
DB_DATABASE = "db"
MYSQL_USE_SSL = "true"
MYSQL_SSL_VERIFY_SERVER_CERT = "false"
CACHE_DRIVE = "file"
SESSION_DRIVER = "file"
COOKIE_PATH = "/"
COOKIE_SECURE = "false"
COOKIE_SAMESITE = "lax"
APP_NAME = "FireflyIII"
BROADCAST_DRIVER = "log"
QUEUE_DRIVER = "sync"
CACHE_PREFIX = "firefly"
TRUSTED_PROXIES = "**"
