app = "whi"
primary_region = "lhr"

[build]
dockerfile = "Dockerfile"

[[vm]]
size = "shared-cpu-1x"
memory = "256MB"

[[restart]]
policy = "never"

[deploy]
strategy = "immediate"

[mounts]
source = "whi_storage"
destination = "/var/www/html/storage"
initial_size = "1GB"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
[http_service.concurrency]
type = "requests"
soft_limit = 10000
[[http_service.checks]]
grace_period = "2s"
interval = "5s"
timeout = "5s"
path = "/health"
headers = { "X-Forwarded-Proto" = "HTTPS" }

[[statics]]
guest_path = "/var/www/html/public/css"
url_prefix = "/css"
[[statics]]
guest_path = "/var/www/html/public/js"
url_prefix = "/js"
[[statics]]
guest_path = "/var/www/html/public/build"
url_prefix = "/build"
[[statics]]
guest_path = "/var/www/html/public/fa"
url_prefix = "/fa"

[env]
APP_ENV = "local"
TZ = "Europe/London"
LOG_CHANNEL = "stack"
APP_NAME = "DataImporter"
BROADCAST_DRIVER = "log"
TRUSTED_PROXIES = "**"
IMPORT_DIR_ALLOWLIST = "/var/www/html/import"
CAN_POST_AUTOIMPORT = "true"
CAN_POST_FILES = "true"
APP_DEBUG = "true"
LOG_LEVEL = "debug"

[[files]]
guest_path = "/var/www/html/import/1.json"
secret_name = "CFG_1"
[[files]]
guest_path = "/var/www/html/import/2.json"
secret_name = "CFG_2"
[[files]]
guest_path = "/var/www/html/import/3.json"
secret_name = "CFG_3"
[[files]]
guest_path = "/var/www/html/import/4.json"
secret_name = "CFG_4"
