name: Firefly
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - entrypoint.sh
      - fly.toml
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
