name: Firefly Data Importer
on:
  push:
    branches:
      - main
    paths:
      - importer/Dockerfile
      - importer/fly.toml
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-importer
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --ha=false
        working-directory: importer
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IMPORTER_API_TOKEN }}
